<?php

return [
    'peopledata'=>['fetcher'=>'PeopledataFetcher', 'manager'=>'PeopledataManager'],
    'myspace'=>['fetcher'=>'MySpaceFetcher', 'manager'=>'MySpaceManager'],
    'soundcloud' => ['fetcher'=>'SoundcloudFetcher', 'manager'=>'SoundcloudManager'],
    'flickr' => ['fetcher'=>'FlickrFetcher', 'manager'=>'FlickrManager'],
    'google' => ['fetcher'=>'GoogleFetcher', 'manager'=>'GoogleManager'],
    'foursquare' => ['fetcher'=>'FoursquareFetcher', 'manager'=>'FoursquareManager'],
    'twitter' => ['fetcher'=>'TwitterFetcher', 'manager'=>'TwitterManager'],
    'instagram' => ['fetcher'=>'InstagramFetcher', 'manager'=>'InstagramManager'],
    'slideshare' => ['fetcher'=>'SlideshareFetcher', 'manager'=>'SlideshareManager'],
    'youtube' => ['fetcher'=>'YoutubeFetcher', 'manager'=>'YoutubeManager'],
    'yellowpages' => ['fetcher'=>'YellowpagesFetcher', 'manager'=>'YellowpagesManager'],
    'pinterest' => ['fetcher'=>'PinterestFetcher', 'manager'=>'PinterestManager'],
    'googleplus' => ['fetcher'=>'GoogleplusFetcher', 'manager'=>'GoogleplusManager'],
    'twitterstatus' => ['fetcher'=>'TwitterstatusFetcher', 'manager'=>'TwitterstatusManager'],
    'gcse' => ['fetcher'=>'GoogleGCSEFetcher', 'manager'=>'GoogleGCSEManager'],
    'fullcontact' => ['fetcher'=>'FullcontactFetcher', 'manager'=>'FullcontactManager'],
    'websites' => ['fetcher'=>'Whois\WhoisFetcher', 'manager'=>'Whois\WhoisManager'],
    'facebook' => ['fetcher'=>'Facebook\FacebookPeopleSearch', 'manager'=>'Facebook\FacebookPeopleManager'],
    'facebook_people_search' => ['fetcher'=>'Facebook\FacebookPeopleSearch', 'manager'=>'Facebook\FacebookPeopleManager'],
    'facebook_live_in' => ['fetcher'=>'Facebook\FacebookPeopleSearch', 'manager'=>'Facebook\FacebookPeopleManager'],
    'facebook_by_relatives' => ['fetcher'=>'Facebook\FacebookPeopleSearch', 'manager'=>'Facebook\FacebookPeopleManager'],
    'facebook_in_friends' => ['fetcher'=>'Facebook\FacebookInFriends', 'manager'=>'Facebook\FacebookInFriendsManager'],
    'linkedin' => ['fetcher'=>'LinkedinFetcher', 'manager'=>'LinkedinManager'],
    'usernames' => ['fetcher'=>'UsernamesFetcher', 'manager'=>'UsernamesManager'],
    'google_image' => ['fetcher'=>'GoogleimageFetcher', 'manager'=>'GoogleimageManager'],
    'angel' => ['fetcher'=>'AngelFetcher', 'manager'=>'AngelManager'],
    'whois' => ['fetcher'=>'Whois\WhoisFetcher', 'manager'=>'Whois\WhoisManager'],
];
